Repository wecode-bootcamp-korea/20-1st-WIKEA-frontend, pull requests merged in 2021-05, with the labels that each got.

#9 [20기 김수연] Add : 초기 세팅 변경
  src/components/README.md
  src/styles/base/_globals.scss
  src/styles/common.scss
  src/styles/layouts/_grids.scss
  src/styles/mixins/_flexbox.scss
  src/styles/mixins/_positions.scss
  src/styles/var.scss
Labels: Status: Accepted

#14 [20기 김수연] Add : 초기 세팅 수정커밋 입니다~!! 한번만 더 Merge부탁드립니다 😂
  src/styles/common.scss
  src/styles/constants/_colors.scss
  src/styles/layouts/_grids.scss
  src/styles/mixins/_responsive.scss
Labels: Status: 도움 요청

#11 [20기 김수연] Footer component 리뷰 반영
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterLine/footerLine.js
  src/components/Footer/FooterList/FooterList.js
Labels: Status: Accepted

#2 [20기 안정현] 로그인 페이지 - ADD(3차) : 레이아웃 및 validation 기능 구현 완료
  public/images/Login/SignIn/wikeaLogo.jpeg
  src/config.js
  src/pages/Login/SignIn/SignIn.js
  src/pages/Login/SignIn/SignIn.scss
  src/styles/base/_reset.scss
  src/styles/var.scss
Labels: Status: Accepted

#6 [20기 김예슬] 사이드 모달창 컴포넌트 - Modify : 1차 리뷰 수정
  src/components/SideModal/README.md
  src/components/SideModal/SideModal.js
  src/components/SideModal/SideModal.scss
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#13 [20기 김예슬] 메인 네비게이션 컴포넌트 - Add :UI 구현, 탭 기능 구현, api 테스트 완료
  src/components/AsideNav/AsideNav.scss
  src/components/MainNavModal/MainNavModal.js
  src/components/MainNavModal/MainNavModal.scss
  src/components/SideModal/README.md
  src/components/SideModal/SideModal.js
Labels: Status: 리뷰 요청

#8 [20기 노선경] Add : breadcrumb
  src/components/Breadcrumb/Breadcrumb.js
  src/components/Breadcrumb/Breadcrumb.scss
  src/pages/Main/Details/Details.js
Labels: Status: 리뷰 요청

#12 [20기 노선경] 상세페이지 - Add : Carousel
  public/images/Detail/logo.png
  src/pages/Main/Details/Modal/ImgModal.js
  src/pages/Main/Details/Modal/ImgModal.scss
  src/pages/Main/Details/Modal/ImgSlider.js
  src/pages/Main/Details/Modal/ImgSlider.scss
  src/pages/Main/Details/Modal/imgData.js
  src/styles/layouts/_grids.scss
  src/styles/mixins/_flexbox.scss
Labels: Status: 리뷰 요청

#3 [20기 김수연] 리스트 페이지 - Add : 리뷰 반영 완료
  public/images/Lists/avator.JPG
  src/pages/Main/Lists/ItemExplanation/ItemExplanation.js
  src/pages/Main/Lists/ItemExplanation/ItemExplanation.scss
  src/pages/Main/Lists/ListBtn/ListBtn.js
  src/pages/Main/Lists/ListBtn/ListBtn.scss
  src/pages/Main/Lists/ListBtn/Sortbox/Sortbox.js
  src/pages/Main/Lists/ListBtn/Sortbox/Sortbox.scss
  src/pages/Main/Lists/Lists.js
  src/pages/Main/Lists/Lists.scss
  src/pages/Main/Lists/Products/Products.js
  src/pages/Main/Lists/Products/Products.scss
  src/styles/layouts/_grids.scss
Labels: Status: Accepted

#5 [20기 김수연] Add : README 수정
  public/data/listmockdata.json
  public/images/Lists/3-removebg-preview.png
  public/images/Lists/3.jpg
  src/components/Product/Product.js
  src/components/Product/Product.scss
  src/components/Product/README.md
Labels: Status: Accepted

#20 [20기 김예슬] Add : SideModal.js, AsideNav.js 복구
  src/components/AsideNav/AsideNav.js
  src/components/SideModal/SideModal.js
Labels: Status: 리뷰 요청

#4 [20기 김예슬] 메인 페이지 - Add : 데이터 구조 변경, 신제품 호버시 애니메이션 추가
  public/data/NewProducts/NewProducts.json
  public/data/NewProducts/NewProducts2.json
  public/data/NewProducts/bgImages.json
  public/images/Detail/README.md
  public/images/Lists/3-removebg-preview.png
  public/images/Lists/3.jpg
  public/images/Lists/README.md
  public/images/Lists/avator.JPG
  public/images/Login/README.md
  public/images/Login/SignIn/wikeaLogo.jpeg
  public/images/Main/README.md
  public/images/bgImages/1.jpeg
  public/images/bgImages/2.jpeg
  public/images/bgImages/visual.png
  public/images/bgimages/1.jpeg
  public/images/bgimages/2.jpeg
  public/images/bgimages/visual.png
  public/images/logo.png
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/Label/Label.js
  src/pages/Main/components/Label/Label.scss
  src/pages/Main/components/NewProduct/NewProduct.js
  src/pages/Main/components/NewProduct/NewProduct.scss
  src/styles/base/_globals.scss
  src/styles/common.scss
  src/styles/layouts/_grids.scss
Labels: Status: Accepted

#7 [20기 노선경] Add : Nav var
  src/Routes.js
  src/components/Nav/Message.js
  src/components/Nav/Message.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Details/Details.js
  src/pages/Main/Details/Modal/CartModal/CartModal.js
  src/pages/Main/Details/Modal/CartModal/CartModal.scss
Labels: Status: Accepted

#15 [20기 김수연] 리스트 페이지 필터 모달 1차 리뷰 반영
  src/pages/Main/Lists/ListBtn/FilterModal/FilterModal.js
  src/pages/Main/Lists/ListBtn/FilterModal/FilterModal.scss
Labels: Status: Accepted

#10 [20기 노선경] Modify : conflict 해결 완료
  public/data/detailsData/test.json
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Details/Details.js
  src/pages/Main/Details/Main/DetailsMain.js
  src/pages/Main/Details/Main/DetailsMain.scss
  src/pages/Main/Details/Main/ItemDetails/ItemDetails.js
  src/pages/Main/Details/Main/ItemDetails/ItemDetails.scss
  src/pages/Main/Details/Main/ItemImg/ItemImg.js
  src/pages/Main/Details/Main/ItemImg/ItemImg.scss
  src/pages/Main/Details/Main/ItemInfo/ItemInfo.js
  src/pages/Main/Details/Main/ItemInfo/ItemInfo.scss
  src/pages/Main/Details/Main/ItemInfo/PrimaryInfo.js
  src/pages/Main/Details/Main/ItemInfo/PrimaryInfo.scss
  src/pages/Main/Details/Modal/CartModal/CartModal.js
  src/pages/Main/Details/Modal/CartModal/CartModal.scss
  src/pages/Main/Details/Modal/DetailsModal/Detail.js
  src/pages/Main/Details/Modal/DetailsModal/Detail.scss
  src/pages/Main/Details/Modal/DetailsModal/DetailsModal.js
  src/pages/Main/Details/Modal/DetailsModal/DetailsModal.scss
  src/pages/Main/Details/Modal/ImgModal.js
  src/pages/Main/Details/Modal/ImgModal/ImgModal.js
  src/pages/Main/Details/Modal/ImgModal/ImgModal.scss
  src/pages/Main/Details/Modal/ImgModal/ImgSlider.js
  src/pages/Main/Details/Modal/ImgModal/ImgSlider.scss
  src/pages/Main/Details/Modal/ImgSlider.scss
  src/pages/Main/Details/Modal/LikePopup/likePopUp.js
  src/pages/Main/Details/Modal/LikePopup/likePopUp.scss
  src/pages/Main/Details/Modal/imgData.js
Labels: Status: Accepted

#16 [20기 김예슬] 공용 컴포넌트 - Modify : 1차 리뷰 수정
  src/components/ScrollBox/ScrollBox.js
  src/components/ScrollBox/ScrollBox.scss
Labels: Status: Accepted

#21 [20기 안정현] 로그인 페이지 - Modify(3차) : conflict 해결 완료
  src/pages/Login/SignIn/SignIn.js
Labels: Status: Accepted

#23 [20기 김수연] Router에 Footer추가
  src/Routes.js
Labels: Status: Accepted

#22 [20기 김예슬] 메인 네비게이션 컴포넌트 - Add : conflict 해결
  public/data/Categories/Categories.json
  public/images/bgImages/1.jpeg
  public/images/bgImages/2.jpeg
  public/images/bgImages/visual.png
  src/Routes.js
  src/components/AsideNav/AsideNav.js
  src/components/AsideNav/AsideNav.scss
  src/components/Footer/Footer.scss
  src/components/MainNavModal/MainNavModal.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/SideModal/SideModal.scss
  src/config.js
  src/pages/Main/Details/Modal/DetailsModal/DetailsModal.js
  src/pages/Main/Lists/ListBtn/ListBtn.js
  src/pages/Main/Lists/Products/Products.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: Accepted
